// Generated by `epochnotes rent template`. Adapt the account type and the authority field; keep the rest.
//
// The staged rent reduction lowers the minimum balance of every account and returns nothing by itself: an
// account funded at an earlier, higher rate keeps the difference. This instruction lets the authority of the
// account take that difference out.
//
// WARNING: it takes EVERYTHING the account holds above the rent-exempt minimum. Use it as it is only for
// accounts whose lamports are a rent deposit and nothing else. If the account also keeps lamports that belong
// to somebody (a vault, an escrow, collected fees), subtract what is owed before computing the excess, or this
// instruction hands those lamports to the authority.

use anchor_lang::prelude::*;

use crate::Vault;

#[derive(Accounts)]
pub struct WithdrawExcess<'info> {
    /// Only the authority stored in the account may withdraw.
    #[account(mut, has_one = authority @ WithdrawExcessError::NotAuthority)]
    pub account: Account<'info, Vault>,
    #[account(mut)]
    pub authority: Signer<'info>,
}

pub fn withdraw_excess(ctx: Context<WithdrawExcess>) -> Result<()> {
    let account = ctx.accounts.account.to_account_info();
    // The minimum is asked from the cluster at run time. A rate compiled into the program goes stale at every
    // step of the reduction, and the reduction is not guaranteed to be one-way.
    let minimum = Rent::get()?.minimum_balance(account.data_len());
    let excess = account.lamports().saturating_sub(minimum);
    require!(excess > 0, WithdrawExcessError::NothingToWithdraw);

    // The program owns the account, so it may debit it directly; the account stays rent-exempt by construction.
    **account.try_borrow_mut_lamports()? -= excess;
    **ctx.accounts.authority.to_account_info().try_borrow_mut_lamports()? += excess;
    Ok(())
}

#[error_code]
pub enum WithdrawExcessError {
    #[msg("Only the authority of the account may withdraw")]
    NotAuthority,
    #[msg("The account holds nothing above the rent-exempt minimum")]
    NothingToWithdraw,
}
