/** What the template is filled with: the account type of the program, and the field of it that holds the authority. */
export interface WithdrawExcessOptions {
  accountType?: string;
  authorityField?: string;
}

const RUST_TYPE = /^[A-Z][A-Za-z0-9]*$/;
const RUST_FIELD = /^[a-z][a-z0-9_]*$/;

/**
 * An Anchor instruction that lets the authority of a program-owned account take out what the account holds
 * above the rent-exempt minimum. The minimum is read from the cluster at run time, so the instruction stays
 * right at every step of the rent reduction, and if the rate is ever raised again. With the default options
 * the text is, byte for byte, `programs/rent-example/src/withdraw_excess.rs`, which is tested on a validator.
 */
export function withdrawExcessTemplate(options: WithdrawExcessOptions = {}): string {
  const accountType = options.accountType ?? 'Vault';
  const authorityField = options.authorityField ?? 'authority';
  if (!RUST_TYPE.test(accountType)) throw new Error(`"${accountType}" is not a Rust type name`);
  if (!RUST_FIELD.test(authorityField)) throw new Error(`"${authorityField}" is not a Rust field name`);
  return `// Generated by \`epochnotes rent template\`. Adapt the account type and the authority field; keep the rest.
//
// The staged rent reduction lowers the minimum balance of every account and returns nothing by itself: an
// account funded at an earlier, higher rate keeps the difference. This instruction lets the authority of the
// account take that difference out, and nothing more.

use anchor_lang::prelude::*;

use crate::${accountType};

#[derive(Accounts)]
pub struct WithdrawExcess<'info> {
    /// Only the authority stored in the account may withdraw.
    #[account(mut, has_one = ${authorityField} @ WithdrawExcessError::NotAuthority)]
    pub account: Account<'info, ${accountType}>,
    #[account(mut)]
    pub ${authorityField}: Signer<'info>,
}

pub fn withdraw_excess(ctx: Context<WithdrawExcess>) -> Result<()> {
    let account = ctx.accounts.account.to_account_info();
    // The minimum is asked from the cluster at run time. A rate compiled into the program goes stale at every
    // step of the reduction, and the reduction is not guaranteed to be one-way.
    let minimum = Rent::get()?.minimum_balance(account.data_len());
    let excess = account.lamports().saturating_sub(minimum);
    require!(excess > 0, WithdrawExcessError::NothingToWithdraw);

    // The program owns the account, so it may debit it directly; the account stays rent-exempt by construction.
    **account.try_borrow_mut_lamports()? -= excess;
    **ctx.accounts.${authorityField}.to_account_info().try_borrow_mut_lamports()? += excess;
    Ok(())
}

#[error_code]
pub enum WithdrawExcessError {
    #[msg("Only the authority of the account may withdraw")]
    NotAuthority,
    #[msg("The account holds nothing above the rent-exempt minimum")]
    NothingToWithdraw,
}
`;
}
